---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action üß™'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: 'lfreleng-actions/test-python-project'
          path: 'test-python-project'

      # Test valid tag comparison
      - name: "Run Action: ${{ github.repository }} [Exact match]"
        uses: ./
        with:
          path_prefix: 'test-python-project/'
          exit_on_fail: 'false'
          test_tag: '0.0.1'

      # Test valid tag comparison (variation)
      - name: "Run Action: ${{ github.repository }} [Strip prefix]"
        uses: ./
        with:
          path_prefix: 'test-python-project/'
          exit_on_fail: 'false'
          test_tag: 'v0.0.1'

      # Test invalid tag comparison
      - name: "Run Action: ${{ github.repository }} [Failure test]"
        uses: ./
        id: failure
        continue-on-error: true
        with:
          path_prefix: 'test-python-project/'
          exit_on_fail: 'true'
          test_tag: '0.1.0'

      # Failure testing is also important
      - name: 'Error if step above did NOT fail'
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo 'Error: previous test step did NOT fail ‚ùå'
          exit 1
